### ISSUE TITLE
s3ql on alpine doesn't work with setuptools >= 47.0

### ISSUE THREAD

**Issue by Salokyn** [s3ql/s3ql#242]
Hi,

I use s3ql within a Docker image.

Based on alpine image, I use the following requirement.txt to build the image:

```
setuptools (=53.0.0 at this time)
cryptography
defusedxml
requests
apsw >= 3.7.0
trio >= 0.15
pyfuse3 >= 3.2.0, < 4.0
dugong >= 3.4, < 4.0
google-auth
google-auth-oauthlib
```

And following Dockerfile:

```Dockerfile
FROM python:3.8-alpine AS build

ARG S3QL_VERSION=3.7.0

COPY requirements.txt /
RUN apk --no-cache add curl gnupg jq bzip2 g++ make pkgconfig fuse3-dev sqlite-dev libffi-dev openssl-dev
RUN pip install --user --ignore-installed -r requirements.txt
RUN gpg2 --batch --keyserver keyserver.ubuntu.com --recv-key 0xD113FCAC3C4E599F
ARG FILE="s3ql-$S3QL_VERSION"
ARG URL="https://github.com/s3ql/s3ql/releases/download/release-$S3QL_VERSION/$FILE.tar.bz2"
RUN set -x; \
    curl -sfL "$URL" -o "/tmp/$FILE.tar.bz2" \
 && curl -sfL "$URL.asc" | gpg2 --batch --verify - "/tmp/$FILE.tar.bz2" \
 && tar -xjf "/tmp/$FILE.tar.bz2"
WORKDIR $FILE
RUN python3 setup.py build_ext --inplace \
 && python3 setup.py install --user

FROM python:3.8-alpine
RUN apk --no-cache add fuse3 psmisc
COPY --from=build /root/.local/bin/ /usr/local/bin/
COPY --from=build /root/.local/lib/ /usr/local/lib/
COPY ./authfile.sh ./entrypoint.sh ./mount.sh /usr/local/bin/
RUN chmod 755 /usr/local/bin/*.sh
ENV MOUNTPOINT=/s3ql
VOLUME /root/.s3ql
HEALTHCHECK CMD ["/bin/sh","-c","s3qlstat --quiet $MOUNTPOINT"]
ENTRYPOINT ["/bin/sh","/usr/local/bin/entrypoint.sh"]
CMD ["/bin/sh","/usr/local/bin/mount.sh"]
```

Build is fine.

But when I use `s3qladm` I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/s3qladm", line 33, in <module>
    sys.exit(load_entry_point('s3ql==3.7.0', 'console_scripts', 's3qladm')())
  File "/usr/local/bin/s3qladm", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 618, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/adm.py", line 18, in <module>
    from .metadata import dump_and_upload_metadata, download_metadata
  File "<frozen zipimport>", line 259, in load_module
  File "/usr/local/lib/python3.8/site-packages/s3ql-3.7.0-py3.8-linux-x86_64.egg/s3ql/metadata.py", line 13, in <module>
    from .deltadump import INTEGER, BLOB, dump_table, load_table
ImportError: cannot import name 'INTEGER' from 's3ql.deltadump' (/root/.cache/Python-Eggs/s3ql-3.7.0-py3.8-linux-x86_64.egg-tmp/s3ql/deltadump.cpython-38-x86_64-linux-gnu.so)
```

It only works with `setuptools < 47.0`. Do you have an idea why ?

**Comment by r0ps3c** [comment]
This is similar/a duplicate of #193. Quickest fix seems to be a downgrade to setuptools ~v47

**Comment by d--j** [comment]
#247 should fix this.

For a quick fix, change
```
RUN python3 setup.py build_ext --inplace \
 && python3 setup.py install --user
```
to
```
RUN sed -i -e 's/zip_safe=True/zip_safe=False/' setup.py \
 && python3 setup.py build_ext --inplace \
 && python3 setup.py install --user
```
